sudo: required
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
script:
- export DOCKER_CLI_EXPERIMENTAL=enabled
- source sha_function.sh
- flag=$(is_base "vmnet8/turtleblocksjs:latest" "vmnet8/nginx:latest")
- echo $flag
- echo "$DOCKERPASS" | docker login -u vmnet8 --password-stdin
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- "./docker-build.sh vmnet8/nginx:latest arm"
- "./docker-build.sh vmnet8/nginx:latest arm64"
- "./docker-build.sh vmnet8/nginx:latest amd64"
before_deploy:
- timetag=$(date +%Y%m%d%H%M)
- echo $timetag
- tag1="latest"
- tag2=$timetag
- echo "timetag is $tag2"
- create_manifest vmnet8/turtleblocksjs $tag1 $tag2 vmnet8/turtleblocksjs-tags:amd64
  vmnet8/turtleblocksjs-tags:arm vmnet8/turtleblocksjs-tags:arm64
- docker manifest inspect vmnet8/turtleblocksjs:$tag1
- docker manifest inspect vmnet8/turtleblocksjs:$tag2
deploy:
- provider: script
  script: docker manifest push vmnet8/turtleblocksjs:$tag1; docker manifest push vmnet8/turtleblocksjs:$tag2
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$flag = true"
env:
  global:
  - secure: V39Hu3egnC8lc57gvxfEA4VVGwqaz+QsccYHvEZEc/v2bkZVW0NcmS5c5C2UnIQGt42Ux/qNehIEl3T/w/fVBmBmWp4Y4AxJUvTxBsv+MONKtVrOZ/YwAxtQUEJ0MTYe3RUrTYqiyDLpc5r9oxqjk6jzaV0HPAWBYz0hhGGAs7+nqn4E12NeXw/quI8rcpdV+t5JSIiE2gzItRHMp0+YKBlK2aO78wnBZ5106F6WOULwGPnFeI49upNGhQmgS+TFWNKs8g5ACO0qZbOUCdFY1mgwACDtqKttJdegxbSAojAwvkgE8nMiyCVcenh6efCDNbZYTiq0IY0OjJF/FvW1fQuXd0nejExiVz7pPQ0mlS7AxRAR+w452bSgZbaRZQfGdS0UudsVVXQ/E4TKqPxN9OsVuaZzZDT5ypHSij0M7q1iBYuP9QCU4/UQqEIBjYAisGRjw4/Q5MX9XKUDm3/H+sO63O0VBFJ9ayMjH/herTFtWQd8v12Dn8hTcKqla1t4NQVso8CAHm6kMsadp2gfBr7DqDFCTYNik6sHIDhFU3czNZ5Hi3MbYTPSWwCnvfuNukIsfEMJGkf4PQejXyVziZ+KBF6J0jjtH0dR1hs0cYd6w1UYjiSjyg52eMyVAl4IyoM6tPsd4WdEX3fT2kt5+XDQpxIqyln4z8mJxa4Get0=
